# Generated by Django 5.2.9 on 2026-06-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_plan_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
