# Generated by Django 5.2.9 on 2026-06-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_plan_plan_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=set(),
        ),
    ]
